// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa-XgRvglWMcpRpUWwmpyNO-u9JPVNJyE',
    appId: '1:413538268008:web:f1d23586cf8caf5eb09cdd',
    messagingSenderId: '413538268008',
    projectId: 'smart-pagination-demo',
    authDomain: 'smart-pagination-demo.firebaseapp.com',
    storageBucket: 'smart-pagination-demo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA28pJmC7wUMQMCvcb6TdpwrJZvLxjvJNI',
    appId: '1:413538268008:android:41bf06f03f6288f7b09cdd',
    messagingSenderId: '413538268008',
    projectId: 'smart-pagination-demo',
    storageBucket: 'smart-pagination-demo.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDa-XgRvglWMcpRpUWwmpyNO-u9JPVNJyE',
    appId: '1:413538268008:web:fc3eb137968c6a83b09cdd',
    messagingSenderId: '413538268008',
    projectId: 'smart-pagination-demo',
    authDomain: 'smart-pagination-demo.firebaseapp.com',
    storageBucket: 'smart-pagination-demo.firebasestorage.app',
  );
}
